#!/usr/bin/env python3
"""The narration as the Narrated film plays it, from the approved takes.

    python3 scripts/prepare-vo.py [--out public/vo] [--ts src/narrated/vo-lines.ts]

Reads narration/vo/<id>.wav (Kokoro-82M af_heart, speed 0.95, one file per line) and narration/words.json
(faster-whisper small.en word timestamps of those files). For every line:
  1. one gain for the whole set (+10.1 dB), 48 kHz, a brick-wall limiter at 0.70 (about -3 dBFS): the set then reads
     about -16 LUFS integrated with a true peak near -1.8 dBTP once the film's sounds sit under it;
  2. the speech edges by silencedetect (-42 dB, 0.12 s);
  3. trimmed to 60 ms before the first sound and 120 ms after the last, with a 20 ms fade in and an 80 ms fade out;
  4. its words re-timed to the trimmed start.
Writes the trimmed WAVs and src/narrated/vo-lines.ts (VO_LINES: id, trimmed length, text, [word, start]).
"""
import argparse
import json
import os
import re
import subprocess
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GAIN_DB = 10.1
LIMIT = "alimiter=limit=0.70:attack=2:release=50:level=disabled"
SILENCE = "silencedetect=n=-42dB:d=0.12"
LEAD, TAIL, FADE_IN, FADE_OUT = 0.06, 0.12, 0.02, 0.08

HEADER = """// The narration (narration/vo/<id>.wav, Kokoro-82M af_heart at speed 0.95, approved by the client), as played in the
// Narrated film: public/vo/<id>.wav is each line normalised as one set (+10.1 dB, limiter at -3 dBFS: about -16 LUFS
// integrated, true peak -1.8 dBTP) and trimmed to its speech (60 ms before the first sound, 120 ms after the last,
// faded). sec is that trimmed length; words are [word, seconds from the trimmed start] from faster-whisper
// (small.en, word timestamps), used to land each line's key word on its picture.
// Generated by scripts/prepare-vo.py.
export type VoLine = { id: string; sec: number; text: string; words: [string, number][] };
export const VO_LINES: VoLine[] = """


def ff(*args):
    subprocess.run(["ffmpeg", "-loglevel", "error", "-y", *args], check=True)


def edges(path):
    err = subprocess.run(["ffmpeg", "-hide_banner", "-i", path, "-af", SILENCE, "-f", "null", "-"], capture_output=True, text=True).stderr
    dur = float(subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", path], capture_output=True, text=True).stdout)
    st = [float(x) for x in re.findall(r"silence_start: ([\d.]+)", err)]
    en = [float(x) for x in re.findall(r"silence_end: ([\d.]+)", err)]
    onset = en[0] if st and st[0] == 0 else 0.0
    offset = st[-1] if st and (len(en) < len(st) or en[-1] >= dur - 0.01) else dur
    return round(dur, 3), round(onset, 3), round(offset, 3)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "public", "vo"))
    ap.add_argument("--ts", default=os.path.join(ROOT, "src", "narrated", "vo-lines.ts"))
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    words = json.load(open(os.path.join(ROOT, "narration", "words.json")))
    lines = []
    with tempfile.TemporaryDirectory() as tmp:
        for l in words:
            src = os.path.join(ROOT, "narration", "vo", l["id"] + ".wav")
            full = os.path.join(tmp, l["id"] + ".wav")
            ff("-i", src, "-af", f"volume={GAIN_DB}dB,aresample=48000,{LIMIT}", "-c:a", "pcm_s16le", full)
            dur, onset, offset = edges(full)
            t0, t1 = max(0, onset - LEAD), min(dur, offset + TAIL)
            ff("-ss", f"{t0:.3f}", "-to", f"{t1:.3f}", "-i", full, "-af", f"afade=t=in:d={FADE_IN},afade=t=out:st={t1 - t0 - FADE_OUT:.3f}:d={FADE_OUT}", "-c:a", "pcm_s16le", os.path.join(a.out, l["id"] + ".wav"))
            w = [[x["w"], round(max(0, x["s"] - t0), 2)] for x in l["words"]]
            w[0][1] = LEAD
            lines.append({"id": l["id"], "sec": round(t1 - t0, 3), "text": l["text"], "words": w})
            print(f"{l['id']:12} {t1 - t0:6.3f} s  (speech {onset:.3f}-{offset:.3f} of {dur:.3f})")
    with open(a.ts, "w") as f:
        f.write(HEADER + json.dumps(lines, indent=1, ensure_ascii=False) + ";\n")
    print(f"{len(lines)} lines, {sum(x['sec'] for x in lines):.1f} s of speech -> {a.out}, {a.ts}")


if __name__ == "__main__":
    main()
