import {
  INK,
  NEVER,
  OFFICE,
  allowed,
  answer,
  buyer,
  coBuyer,
  computed,
  date,
  dealer,
  marker,
  none,
  signature,
  statik,
  vehicle,
  when,
  type Condition,
  type DocumentMap,
} from "@/lib/documents/field-maps/types";
import { entityApplicant, hasCoBuyer, personApplicant, titleCarriesLien, tradeIn } from "@/lib/documents/field-maps/conditions";

/** A box the state form has for other kinds of application, never on a sale here. */
const notOnACorridorSale: Condition = () => false;

/**
 * Form 130-U (Rev 01/25), the state's own PDF: 98 AcroForm fields, all on
 * page 1; page 2 is the state's instructions; page 3 is appended only when
 * the buyer's ID photo is on file. Ids are the `AgreementData` keys
 * `buildAgreementData` produces from the filed payload (fill-130u).
 */
export const FORM_130U_MAP: DocumentMap = {
  documentType: "form130U",
  kind: "stateForm",
  template: "public/forms/130-U.pdf",
  askOrder: [
    "form130U.countyOfResidence",
    "form130U.applicationType",
    "form130U.applicantType",
    "form130U.businessName",
    "form130U.businessFein",
    "form130U.emptyWeight",
    "form130U.carryingCapacity",
    "form130U.renewalReminders",
  ],
  pages: [
    {
      page: 1,
      title: "Application For Texas Title And/Or Registration",
      fields: [
        { id: "applying_for", label: "Applying For", source: answer("form130U.applicationType"), blank: NEVER, acroField: "Title  Registration", acroFields: ["Title Only", "Registration Purposes Only", "Nontitle Registration"] },
        { id: "vin", label: "1. Vehicle Identification Number", source: vehicle("vin"), blank: NEVER, acroField: "1 Vehicle Identification Number" },
        { id: "year", label: "2. Year", source: vehicle("year"), blank: NEVER, acroField: "2 Year" },
        { id: "make", label: "3. Make", source: vehicle("make"), blank: NEVER, acroField: "3 Make" },
        { id: "body_style", label: "4. Body Style", source: vehicle("bodyStyle"), blank: NEVER, acroField: "4 Body Style" },
        { id: "model", label: "5. Model", source: vehicle("model"), blank: NEVER, acroField: "5 Model" },
        { id: "major_color", label: "6. Major Color", source: vehicle("exteriorColor"), blank: NEVER, acroField: "6 Major Color" },
        { id: "minor_color", label: "7. Minor Color", source: none("the vehicle row has one colour"), blank: allowed("optional on the form"), acroField: "7 Minor Color" },
        { id: "tx_plate_no", label: "8. Texas License Plate No.", source: answer("guide:plate.plate"), blank: when("a plate is recorded"), acroField: "8 Texas License Plate No" },
        { id: "odometer", label: "9. Odometer Reading", source: vehicle("mileage"), blank: NEVER, acroField: "9 Odometer Reading no tenths" },
        { id: "odometer_brand", label: "10. Odometer Brand", source: answer("billOfSale.odometerStatus"), blank: NEVER, acroField: "Not Actual", acroFields: ["Exceeds Mechanical Limits"] },
        { id: "empty_weight", label: "11. Empty Weight", source: answer("form130U.emptyWeight"), blank: NEVER, acroField: "11 Empty Weight" },
        { id: "carrying_capacity", label: "12. Carrying Capacity (if any)", source: answer("form130U.carryingCapacity"), blank: allowed("(if any)"), acroField: "12 Carrying Capacity if any" },
        { id: "applicant_type", label: "13. Applicant Type", source: answer("form130U.applicantType"), blank: NEVER, acroField: "Individual", acroFields: ["Business", "Government", "Trust", "NonProfit"] },
        // A person is identified by their photo ID (boxes 14 and 15); an
        // entity by its FEIN in box 14 and no ID type at all.
        { id: "buyer_dl_number", label: "14. Applicant Photo ID Number", source: buyer("idNumber"), on: personApplicant, blank: NEVER, acroField: "14 Applicant Photo ID Number or FEINEIN" },
        { id: "buyer_fein", label: "14. FEIN/EIN", source: answer("form130U.businessFein"), on: entityApplicant, blank: NEVER },
        { id: "buyer_id_kind", label: "15. Applicant Photo ID Type", source: buyer("idKind"), on: personApplicant, blank: NEVER, acroField: "U.S. Driver License/ID Card", acroFields: ["Passport", "US Military ID", "Passport Issued"] },
        { id: "buyer_dl_state", label: "15. ID Issued By", source: answer("billOfSale.buyerLicenseState"), fallback: buyer("idIssuer"), on: personApplicant, blank: when("a document a state or country issued"), acroField: "State of ID/DL" },
        { id: "buyer_first_name", label: "16. Applicant First Name", source: buyer("nameParts"), on: personApplicant, blank: NEVER, acroField: "16 Applicant First Name or Entity Name Middle Name Last Name Suffix if any" },
        { id: "buyer_middle_name", label: "16. Middle Name", source: buyer("nameParts"), on: personApplicant, blank: when("the buyer has a middle name") },
        { id: "buyer_last_name", label: "16. Last Name", source: buyer("nameParts"), on: personApplicant, blank: NEVER },
        { id: "buyer_suffix", label: "16. Suffix (if any)", source: buyer("nameParts"), on: personApplicant, blank: allowed("(if any)") },
        { id: "buyer_entity_name", label: "16. Entity Name", source: answer("form130U.businessName"), on: entityApplicant, blank: NEVER },
        { id: "co_buyer_name", label: "17. Additional Applicant", source: coBuyer("name"), on: hasCoBuyer, blank: NEVER, acroField: "17 Additional Applicant First Name if applicable Middle Name Last Name Suffix if any", acroFields: ["Additional Applicant", "Date_3"] },
        { id: "buyer_address", label: "18. Applicant Mailing Address", source: buyer("street"), blank: NEVER, acroField: "18 Applicant Mailing Address City State Zip" },
        { id: "buyer_city", label: "18. City", source: buyer("city"), blank: NEVER },
        { id: "buyer_state", label: "18. State", source: buyer("state"), blank: NEVER },
        { id: "buyer_zip", label: "18. Zip", source: buyer("zip"), blank: NEVER },
        { id: "buyer_county", label: "19. Applicant County of Residence", source: answer("form130U.countyOfResidence"), blank: NEVER, acroField: "19 Applicant County of Residence" },
        { id: "previous_owner_name", label: "20. Previous Owner", source: dealer("legalName"), blank: NEVER, acroField: "20 Previous Owner Name or Entity Name City State" },
        { id: "dealer_gdn", label: "21. Dealer GDN", source: dealer("license"), blank: marker("license"), acroField: "21 Dealer GDN if applicable" },
        { id: "buyer_phone", label: "25. Applicant Phone Number (optional)", source: buyer("phone"), blank: allowed("(optional)"), acroField: "25 Applicant Phone Number optional" },
        { id: "buyer_email", label: "26. Email (optional)", source: buyer("email"), blank: allowed("(optional)"), acroField: "26 Email optional" },
        { id: "e_reminder", label: "27. Registration Renewal eReminder", source: answer("form130U.renewalReminders"), blank: when("an email is on file and the buyer said yes"), acroField: "Yes Provide Email in 26" },
        { id: "etitle_lienholder_id", label: "32. Certified/eTitle Lienholder ID", source: dealer("etitleLienholderId"), blank: allowed("(if any)"), acroField: "32 CertifiedeTitle Lienholder ID Number if any" },
        { id: "lien_date", label: "33. First Lien Date", source: date("lienDate"), on: titleCarriesLien, blank: NEVER, acroField: "33 First Lien Date if any" },
        { id: "lienholder_name", label: "34. First Lienholder", source: computed("lien.lienholder"), on: titleCarriesLien, blank: NEVER, acroField: "34 First Lienholder Name if any Mailing Address City State Zip" },
        { id: "lienholder_address", label: "34. Lienholder Mailing Address", source: computed("lien.lienholder"), on: titleCarriesLien, blank: when("the lienholder's address is on file") },
        { id: "lienholder_city", label: "34. City", source: computed("lien.lienholder"), on: titleCarriesLien, blank: when("the lienholder's address is on file") },
        { id: "lienholder_state", label: "34. State", source: computed("lien.lienholder"), on: titleCarriesLien, blank: when("the lienholder's address is on file") },
        { id: "lienholder_zip", label: "34. Zip", source: computed("lien.lienholder"), on: titleCarriesLien, blank: when("the lienholder's address is on file") },
        { id: "trade_in_amount", label: "36. Trade-In (if any)", source: answer("billOfSale.tradeInAllowance"), blank: when("tradeIn=yes", tradeIn), acroField: "Trade-in (if any)" },
        { id: "trade_in_description", label: "36. Trade-In Year / Make", source: answer("billOfSale.tradeInDescription"), blank: when("tradeIn=yes", tradeIn), acroField: "36 TradeIn if any Year Make Vehicle Identification Number" },
        { id: "trade_in_vin", label: "36. Trade-In VIN", source: answer("billOfSale.tradeInVin"), on: tradeIn, blank: when("tradeIn=yes and a VIN was given") },
        { id: "rebate_amount", label: "38(a) Rebate Amount", source: none("no rebate on a used sale here"), on: notOnACorridorSale, blank: allowed("(if any)"), acroField: "Rebate Amount" },
        { id: "sale_price", label: "38(a) Sales Price", source: computed("money.salePrice"), blank: NEVER, acroField: "Sales Price Minus Rebate Amount" },
        { id: "trade_in_amount_38b", label: "38(b) Less Trade-In Amount", source: answer("billOfSale.tradeInAllowance"), blank: when("tradeIn=yes", tradeIn), acroField: "Trade In Amount" },
        { id: "dealer_signer_name", label: "Seller Printed Name", source: dealer("signerName"), blank: marker("signerName"), acroField: "Seller  Name" },
        { id: "sale_date", label: "Date (Seller, Applicant)", source: date("saleDate"), blank: NEVER, acroField: "Date", acroFields: ["Date_2"] },
        { id: "vehicle_location", label: "29. Vehicle Location (if different)", source: none("the vehicle is kept at the applicant's address: blank means box 18"), on: notOnACorridorSale, blank: allowed("if different"), acroField: "29 Vehicle Location Address if different City State Zip" },
        // One line, two sources: a person's whole name, or the entity's name (as box 16).
        { id: "applicant_printed_name", label: "Applicant Printed Name", source: buyer("name"), on: personApplicant, blank: NEVER, acroField: "Applicant Owner" },
        { id: "applicant_printed_entity", label: "Applicant Printed Name", source: answer("form130U.businessName"), on: entityApplicant, blank: NEVER },
        { id: "seller_signature", label: "Signature of Seller", source: signature("dealer"), blank: INK },
        { id: "applicant_signature", label: "Signature of Applicant/Owner", source: signature("buyer"), blank: INK },
      ],
    },
    {
      page: 2,
      title: "TxDMV Instructions",
      fields: [{ id: "instructions", label: "Form 130-U Instructions", source: statik("state artwork"), blank: { allowed: "printed by the state" }, printed: false }],
    },
  ],
  notOnThisDesk: {
    "Vehicle Description": "corrected-title reason; not a sale",
    "AddRemove Lien": "corrected-title reason; not a sale",
    Other: "corrected-title reason; not a sale",
    "Other Reason For Correction": "corrected-title reason; not a sale",
    Exempt: "box 10 exempt: the rule needs the owner and TxDMV (D-08), never inferred",
    "NATO ID": "box 15: an ID kind the intake does not record",
    "Other Military Status of Forces Photo ID": "box 15: an ID kind the intake does not record",
    "US Dept of State ID": "box 15: an ID kind the intake does not record",
    "US Dept of Homeland Security ID": "box 15: an ID kind the intake does not record",
    "U.S. Citizenship & Immigration Services/DOJ ID": "box 15: an ID kind the intake does not record",
    "Permit Number": "box 35: left for the tax office",
    "GDN or Lessor Number": "box 35: left for the tax office",
    "I Hold Motor Vehicle Retailer (Rental) Permit Number": "box 35: left for the tax office",
    "Yes, I am a dealer or lessor that qualifies to take the Fair Market Value Deduction": "box 35: left for the tax office",
    "22. Unit Number (if applicable)": "fleet unit numbers; not a retail sale",
    "23 Renewal Recipient First Name or Entity Name if different Middle Name Last Name Suffix if any": "blank means the applicant",
    "24 Renewal Notice Mailing Address if different City State Zip": "blank means box 18",
    "Yes Attach Form VTR-216": "communication impediment: the desk produces no VTR-216",
    "Yes Attach Form VTR-267": "one lien per sale",
    "Yes Cannot check 30": "electronic title request: not offered",
    "Additional Trade ins": "one trade-in per sale",
    "Sales and Use Tax": "box 38 check: owner and county to confirm (D-08)",
    "For Dealers/Lessors/Rental Only - Fair Market Value Deduction Described in Box 36": "dealers and lessors only",
    "Taxable Amount": "38(d): the county computes it (owner's instruction)",
    "6.25% Tax on Taxable Amount": "38(e): the county computes it",
    "Late Tax Payment Penalty of 5% or": "38(f): the tax office",
    "Late Tax Payment Penalty of 10%": "38(f): the tax office",
    "Late Tax Payment Penalty Amount": "38(f): the tax office",
    "State Taxes Were Paid To": "38(g): the tax office",
    "Amount of Taxes Paid to Previous State": "38(g): the tax office",
    "Amount of Tax and Penalty Due": "38(h): the county computes it",
    "$90 New Resident Tax  Previous State": "not a dealer sale",
    "Resident's previous state": "not a dealer sale",
    "$5 Even Trade Tax": "not a dealer sale",
    "$10 Gift Tax  Attach Comptroller Form 14-317": "not a dealer sale",
    "$65 Rebuilt Salvage Fee": "owner and TxDMV to confirm on a rebuilt resale (D-08)",
    "2.5% Emissions Fee Diesel Vehicles 1996 and Older greater than 14000 lbs": "the lot sells nothing over 14,000 lb",
    "2.5% Emissions Fee": "the lot sells nothing over 14,000 lb",
    "1% Emissions Fee Diesel Vehicles 1997 and Newer greater than 14000 lbs": "the lot sells nothing over 14,000 lb",
    "1% Emissions Fee": "the lot sells nothing over 14,000 lb",
    "Exemption claimed under the Motor Vehicle Sales and Use Tax Law because": "no exemption on a retail sale",
    "Sales Tax Exemption Reason": "no exemption on a retail sale",
    "$28 or $33 Application Fee for Texas Title - contact your county for the correct fee": "the county's to tick (D-08)",
    "Check if applicable I have physically inspected the vehicle described and verified the vehicle identification number above": "optional applicant certification",
    "The vehicle is unrecovered stolen, and I am unable to verify the vehicle identification number above": "not applicable to a sale",
    "I certify I am applying for a corrected title and the original Texas Certificate of Title is lost or destroyed": "not applicable to a sale",
  },
};

/** Box 10 and the other boxes the county leaves to itself are noted for the review. */
export const FORM_130U_OFFICE_FIELDS = ["Taxable Amount", "6.25% Tax on Taxable Amount", "Amount of Tax and Penalty Due"] as const;
export const FORM_130U_OFFICE_BLANK = OFFICE;
