#!/usr/bin/env python3
"""The narration as the Narrated film plays it, from the approved takes (runbook step N6; narration.md section 4).

    python3 scripts/voice/prepare-vo.py --project $P [--gain-db X --why "..."] [--dry-run]

Reads  $P/narration/vo/<id>.wav (the approved takes) and $P/narration/words.json (transcribe.py, small.en).
1. ONE gain for the whole set, computed, never copied from another client: g0 = -16 - LUFS(the raw takes played back to
   back); the set is processed at g0 (48 kHz, the brick-wall limiter at 0.70, trimmed as in 2), measured again, and the
   gain corrected by what the limiter and the trim changed, at most three times, until the set reads -16.0 +/- 0.1.
   Discount's takes give about +9.9 dB (its approved set was made at +10.1 dB by hand and reads -15.9 LUFS).
2. The speech edges by silencedetect (-42 dB, 0.12 s); each line trimmed to 60 ms before its first sound and 120 ms
   after its last, with a 20 ms fade in and an 80 ms fade out; its words re-timed to the trimmed start.
3. The trimmed set, back to back, must read -16 +/- 0.5 LUFS integrated with a true peak <= -1.5 dBTP; else exit 1.
Writes $P/public/vo/<id>.wav and $P/src/narrated/vo-lines.ts (VO_LINES: id, trimmed length, text, [word, start]).
--gain-db overrides step 1 (with --why, printed into vo-lines.ts); --dry-run measures and prints, writing nothing.
"""
import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

sys.dont_write_bytecode = True  # keep the skill folder free of __pycache__
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import LEVEL, ebur128, ffmpeg, load_json  # noqa: E402

LIMIT = "alimiter=limit=0.70:attack=2:release=50:level=disabled"
SILENCE = "silencedetect=n=-42dB:d=0.12"
LEAD, TAIL, FADE_IN, FADE_OUT = 0.06, 0.12, 0.02, 0.08

HEADER = """// The narration as the Narrated film plays it: public/vo/<id>.wav is each approved take (narration/vo/<id>.wav,
// Kokoro-82M {voice}) with one gain for the whole set ({gain:+.1f} dB, {gain_why}) at 48 kHz and a limiter at 0.70, trimmed
// to its speech (60 ms before the first sound, 120 ms after the last, faded). The trimmed set reads {lufs:.1f} LUFS
// integrated, true peak {tp:.1f} dBTP. sec is the trimmed length; words are [word, seconds from the trimmed start] from
// faster-whisper (small.en, word timestamps), used to land each line's key word on its picture.
// Generated by recordly-demo scripts/voice/prepare-vo.py: re-run it, never edit this file.
export type VoLine = {{ id: string; sec: number; text: string; words: [string, number][] }};
export const VO_LINES: VoLine[] = """


def edges(path):
    err = subprocess.run(["ffmpeg", "-nostdin", "-hide_banner", "-i", path, "-af", SILENCE, "-f", "null", "-"],
                         capture_output=True, text=True).stderr
    dur = float(subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", path],
                               capture_output=True, text=True).stdout)
    st = [float(x) for x in re.findall(r"silence_start: ([\d.]+)", err)]
    en = [float(x) for x in re.findall(r"silence_end: ([\d.]+)", err)]
    onset = en[0] if st and st[0] == 0 else 0.0
    offset = st[-1] if st and (len(en) < len(st) or en[-1] >= dur - 0.01) else dur
    return round(dur, 3), round(onset, 3), round(offset, 3)


def process(src_dir, ids, gain, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    outs = []
    for i in ids:
        o = os.path.join(out_dir, i + ".wav")
        ffmpeg("-i", os.path.join(src_dir, i + ".wav"), "-af", f"volume={gain:.2f}dB,aresample=48000,{LIMIT}", "-c:a", "pcm_s16le", o)
        outs.append(o)
    return outs


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--project", required=True)
    ap.add_argument("--gain-db", type=float)
    ap.add_argument("--why", default="")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    P = os.path.abspath(a.project)
    nar = os.path.join(P, "narration")
    src = os.path.join(nar, "vo")
    words = load_json(os.path.join(nar, "words.json"))
    ids = [l["id"] for l in words]
    missing = [i for i in ids if not os.path.exists(os.path.join(src, i + ".wav"))]
    if missing:
        raise SystemExit(f"missing takes: {missing}")
    voice = "af_heart at speed 0.95"
    inputs = os.path.join(P, "client-inputs.json")
    if os.path.exists(inputs):
        v = (load_json(inputs) or {}).get("voice")
        if v:
            voice = f"{v.get('voice')} at speed {v.get('speed')} ({v.get('why')})"

    raw_lufs, raw_tp = ebur128([os.path.join(src, i + ".wav") for i in ids], pre_filter="aresample=48000")
    print(f"raw set: {raw_lufs:.1f} LUFS integrated, true peak {raw_tp:.1f} dBTP ({len(ids)} takes)")
    with tempfile.TemporaryDirectory() as tmp:
        def make(gain, tag):
            """the set at this gain, limited and trimmed: (LUFS, true peak, lines, trimmed dir) of the trimmed set"""
            full = process(src, ids, gain, os.path.join(tmp, tag + "-full"))
            tdir = os.path.join(tmp, tag)
            os.makedirs(tdir)
            rows = []
            for l, f in zip(words, full):
                dur, onset, offset = edges(f)
                t0, t1 = max(0, onset - LEAD), min(dur, offset + TAIL)
                ffmpeg("-ss", f"{t0:.3f}", "-to", f"{t1:.3f}", "-i", f, "-af",
                       f"afade=t=in:d={FADE_IN},afade=t=out:st={t1 - t0 - FADE_OUT:.3f}:d={FADE_OUT}", "-c:a", "pcm_s16le",
                       os.path.join(tdir, l["id"] + ".wav"))
                w = [[x["w"], round(max(0, x["s"] - t0), 2)] for x in l["words"]]
                if w:
                    w[0][1] = LEAD
                rows.append({"id": l["id"], "sec": round(t1 - t0, 3), "text": l["text"], "words": w,
                             "_edges": (onset, offset, dur)})
            lu, pk = ebur128([os.path.join(tdir, i + ".wav") for i in ids])
            return lu, pk, rows, tdir

        if a.gain_db is not None:
            if not a.why.strip():
                raise SystemExit("--gain-db needs --why (a set gain is a decision; it is printed into vo-lines.ts)")
            gain, gain_why = a.gain_db, "set by hand: " + a.why.strip()
        else:
            gain = round(LEVEL["lufs"] - raw_lufs, 1)
            print(f"gain: start at -16 - ({raw_lufs:.1f}) = {gain:+.1f} dB")
            for k in range(3):  # the limiter and the trim move the result: correct until it reads -16.0 +/- 0.1
                lk, _, _, _ = make(gain, f"pass{k}")
                print(f"  at {gain:+.1f} dB the limited, trimmed set reads {lk:.2f} LUFS")
                if abs(lk - LEVEL["lufs"]) <= 0.1:
                    break
                gain = round(gain + (LEVEL["lufs"] - lk), 1)
            gain_why = f"computed from the raw takes ({raw_lufs:.1f} LUFS) to read -16 LUFS after the limiter and the trim"
        lufs, tp, lines, trimmed_dir = make(gain, "final")
        for l in lines:
            onset, offset, dur = l.pop("_edges")
            print(f"  {l['id']:14} {l['sec']:6.3f} s  (speech {onset:.3f}-{offset:.3f} of {dur:.3f})")
        ok = abs(lufs - LEVEL["lufs"]) <= LEVEL["lufs_tol"] and tp <= LEVEL["tp_max"]
        print(f"trimmed set: {lufs:.2f} LUFS integrated (target {LEVEL['lufs']} +/- {LEVEL['lufs_tol']}), "
              f"true peak {tp:.2f} dBTP (max {LEVEL['tp_max']}) -> {'PASS' if ok else 'FAIL'}")
        if not ok:
            print("LEVELS FAIL: nothing written. Check the takes (a clipped or near-silent take skews the set), then re-run.")
            return 1
        if a.dry_run:
            print(f"dry run: gain {gain:+.1f} dB, nothing written")
            return 0
        out = os.path.join(P, "public", "vo")
        os.makedirs(out, exist_ok=True)
        for i in ids:
            shutil.copyfile(os.path.join(trimmed_dir, i + ".wav"), os.path.join(out, i + ".wav"))
    ts = os.path.join(P, "src", "narrated", "vo-lines.ts")
    os.makedirs(os.path.dirname(ts), exist_ok=True)
    with open(ts, "w", encoding="utf8") as f:
        f.write(HEADER.format(voice=voice, gain=gain, gain_why=gain_why, lufs=lufs, tp=tp)
                + json.dumps(lines, indent=1, ensure_ascii=False) + ";\n")
    print(f"VO READY: {len(lines)} lines, {sum(x['sec'] for x in lines):.1f} s of speech, gain {gain:+.1f} dB -> {out}, {ts}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
